export const DASHBOARD = [
  "Revenue",
  "Profit",
  "Refund",
  "Paid For Driver",
  "Total Booking Detail",
  "Total Booking Detail Completed",
  "Total Booking Detail Cancelled",
  "Total Booking Detail Pending",
  "Total Booking Detail Drvier",
  "Total Booking Detail Drvier Completed",
  "Total Booking Detail Drvier Cancelled",
  "Total Booking Detail Drvier Pending",
  "Total Report",
  "Total Report Driver",
  "Total Report Booker",
];

export const LABEL_CHART = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
